# Generated by Django 3.1.3 on 2020-11-05 14:01

from django.db import migrations, models
import django.db.models.deletion
import viewflow_rest.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_class', viewflow_rest.fields.FlowReferenceField(max_length=63, verbose_name='Flow')),
                ('status', models.CharField(choices=[('NEW', '创建了'), ('STARTED', '开始了'), ('DONE', '结束了'), ('CANCELED', '取消了')], max_length=15, verbose_name='状态')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('finished_datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=31, verbose_name='候选人姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='候选人性别')),
            ],
            options={
                'verbose_name': '招聘流程',
                'verbose_name_plural': '招聘流程',
            },
        ),
        migrations.CreateModel(
            name='HireTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_task', viewflow_rest.fields.TaskReferenceField(max_length=63, verbose_name='Task')),
                ('flow_task_type', models.CharField(max_length=31, verbose_name='类型')),
                ('status', models.CharField(choices=[('NEW', '创建了'), ('STARTED', '开始了'), ('DONE', '结束了'), ('CANCELED', '取消了')], max_length=15, verbose_name='状态')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('finished_datetime', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hire.hireprocess')),
            ],
            options={
                'verbose_name': '招聘任务',
                'verbose_name_plural': '招聘任务',
            },
        ),
    ]
