# Generated by Django 3.1.3 on 2020-11-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_hiretask_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireprocess',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
