# Generated by Django 3.1.3 on 2020-11-07 02:39

from django.db import migrations
import viewflow_rest.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20201107_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireprocess',
            name='flow_class',
            field=viewflow_rest.fields.FlowReferenceField(verbose_name='Flow'),
        ),
        migrations.AlterField(
            model_name='hiretask',
            name='flow_task',
            field=viewflow_rest.fields.TaskReferenceField(verbose_name='Task'),
        ),
    ]
