# Generated by Django 3.1.3 on 2020-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0007_hireprocess_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireprocess',
            name='notified',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否已经发送offer通知'),
        ),
    ]
