# Generated by Django 3.1.3 on 2020-11-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretask',
            name='previous',
            field=models.ManyToManyField(related_name='leading', to='hire.HireTask', verbose_name='上级任务'),
        ),
    ]
