# Generated by Django 3.1.3 on 2020-11-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_hireprocess_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireprocess',
            old_name='finished_datetime',
            new_name='finish_datetime',
        ),
        migrations.RenameField(
            model_name='hiretask',
            old_name='finished_datetime',
            new_name='finish_datetime',
        ),
    ]
