# Generated by Django 3.1.3 on 2020-11-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0006_hireprocess_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireprocess',
            name='notified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
