# Generated by Django 3.1.3 on 2020-11-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0010_hiretask_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireprocess',
            name='status',
            field=models.CharField(choices=[('NEW', '创建了'), ('STARTED', '开始了'), ('DONE', '结束了'), ('CANCELED', '取消了')], default='STARTED', max_length=15, verbose_name='状态'),
        ),
    ]
