# Generated by Django 4.0.5 on 2022-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0011_auto_20201109_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireprocess',
            name='status',
            field=models.CharField(choices=[('NEW', '创建了'), ('STARTED', '开始了'), ('DONE', '结束了'), ('CANCELED', '取消了')], default='STARTED', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='hiretask',
            name='flow_task_type',
            field=models.CharField(max_length=31, verbose_name='flow_task_type'),
        ),
        migrations.AlterField(
            model_name='hiretask',
            name='status',
            field=models.CharField(choices=[('NEW', '创建了'), ('STARTED', '开始了'), ('DONE', '结束了'), ('CANCELED', '取消了')], max_length=15, verbose_name='status'),
        ),
    ]
